<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\domain\domain.csproj" />
  </ItemGroup>
	
	<ItemGroup>
		<None Update="EmailTemplates\**\*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Configs\**\*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Resources\**\*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="microsoft.entityframeworkcore" Version="8.0.20" />
    <PackageReference Include="microsoft.extensions.caching.memory" Version="8.0.1" />
    <PackageReference Include="microsoft.extensions.configuration" Version="8.0.0" />
    <PackageReference Include="microsoft.extensions.configuration.binder" Version="8.0.2" />
    <PackageReference Include="newtonsoft.json" Version="13.0.4" />
    <PackageReference Include="npgsql.entityframeworkcore.postgresql" Version="8.0.11" />
    <PackageReference Include="serilog" Version="4.2.0" />
    <PackageReference Include="system.identitymodel.tokens.jwt" Version="8.15.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
